app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
	$array = array(1 => "arimoto", 2 => "Fumimaro");
	//var_dump($array);
	
    return view('welcome');
});


/**
 * DDDの勉強ここから
 */
Route::get('cart',  'CartController@index');
Route::post('cart', 'CartController@addCart');
Route::get('cart/cart', 'CartController@cart');



Route::get('/vue', function () {
	return view('vue');
});

Route::get('/spa', function () {
	return view('spa');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::resource('keihi', 'KeihiController');



Route::get('user', 'UserController@index');
Route::get('user/index', 'UserController@index');
Route::get('user/login', 'UserController@login');
Route::post('user/login', 'UserController@auth');
Route::get('user/logout', 'UserController@logout');

/**
 * Admin関連
 */
Route::get('admin',        'AdminController@index');
Route::get('admin/index',  'AdminController@index');
Route::post('admin/login', 'AdminController@auth');
Route::get('admin/login',  'AdminController@login');
Route::get('admin/logout', 'AdminController@logout');

//Route::group(['middleware' => ['guest:admin'], "prefix" => 'admin'], function () {

	
	
	/**
	 * テスト登録
	 */
	Route::post('/balance/add', 'AdminBalanceController@store');
	Route::get('/balance', 'AdminBalanceController@index');
	Route::get('/balance/add', 'AdminBalanceController@add');

//});

app/Admin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Admin extends Authenticatable
{
    //
	protected $fillable = [
			'name1', 'name2', 'email', 'password',
	];
}

app/Column.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Column extends Model
{
    //
	protected $fillable = [
			'title', 'article', 'image', 'status', 'contribute_date', 'width', 'height'
	];
}

app/Keihi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Keihi extends Model
{
    //
	protected $table = 'keihi';
	
	protected $fillable = [
			'title', 'price', 'url'
	];
}

app/Report.php
<?php
namespace App;

use Illuminate\Filesystem\Filesystem;

class Report
{
	
	protected $file;
	
	public function __construct(Filesystem $file)
	{
		$this->file = $file;
	}
	
	public function output()
	{
		return $this->file->put('report.txt', 'report');
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name1', 'name2', 'company', 'position', 'email', 'password', 'status', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AdminController extends Controller
{
	/**
	 * コンストラクタ
	 */
	public function __construct(){
		
		$this->middleware('guest:admin', ['except' => ['login', 'auth']]);

	}
	
	/**
	 * 認証　
	 * 最終的にはMiddleWareに統合
	 */
	public function authAdmin(){
		if (! \Auth::guard('admin')->check()) {
			return redirect('admin/login');
		}
	}
	
    /**
     * Index
     */
	public function index() { 
		/*
		if (! \Auth::guard('admin')->check()) {
			return redirect('admin/login');
		}
		*/
		return view('admin/index');
	}
	
	/**
	 * login
	 */
	public function login() {
		return view('admin/login');
	}
	
	/**
	 * Auth
	 */
	public function auth(Request $request) {
		$input = $request->all();
		
		$rules = [
				'email'=>'required',
				'password'=>'required',
		];
		 
		$messages = [
				'email.required'=>'email is must.',
				'password.required'=>'password is must.',
		];
		
		$validation = \Validator::make($input,$rules,$messages);
		
		if(\Auth::guard('admin')->attempt(['email'=>$input['email'],'password'=>$input['password']])) {
			return redirect('admin/index');
		} else {
			\Session::flash('flash_message', 'ログインできません');
			return view('admin/login');
		}
	}
	
	/**
	 * Logout
	 */
	public function logout() {
		\Auth::guard('admin')->logout();
		\Session::flash('flash_message', 'ログアウトしました');
		return view('admin/login');
		
	}
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use package\shop\Application\Servies\ItemService;
use package\shop\Application\Servies\AddItemToCart;
use package\shop\Application\Servies\CartService;

class CartController extends Controller
{
    //
    private $item_service;
    
    public function __construct(ItemService $item_service, 
    		                    CartService $cart_service)
    {
    	$this->item_service = $item_service;
    	$this->cart_service = $cart_service;
    }
    
    public function index()
    {
    	$results = $this->item_service->getList();
    	
    	return view('cart.index',  
    			    ['results'  => $results]);
    }
    
    public function cart()
    {
    	$cart = $this->cart_service->getCart();
    	
    	$results = $cart->getCart();
    	
    	return view('cart.cart',
    	            ['results'  => $results]);
    }
    
    public function addCart(Request $request, AddItemToCart $service)
    {
    	$this->validate($request, [
    			'item_id' => 'required|integer',
    			'count'   => 'required|integer'
    	]);
    	
    	$service->add($request->get('item_id'),
    			      $request->get('count'));
    	
    	return redirect("/cart/cart");
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/column/add.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <h2>コラム追加</h2>
  
  
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    
    
    
  {!! Form::open(array('files' => true)) !!}
  
    <div class="form-group">
      {!! Form::label('title', 'タイトル:') !!}
      {!! Form::text('title', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('image', '画像:') !!}
      {!! Form::file('image', null) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('article', '本文:') !!}
      {!! Form::textarea('article', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('width', '横幅:') !!}
      {!! Form::text('width', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('height', '高さ:') !!}
      {!! Form::text('height', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('contribute_date', '投稿日時:') !!}
      {!! Form::text('contribute_date', date("Y-m-d H:i:s"), ['class' => 'form-control ckeditor']) !!}
    </div>
    
    
    <!--  
    <div class="form-group">
      {!! Form::label('ステータス', 'ステータス:') !!}
    
      {!! Form::radio('status', '1', true) !!}有効　
      {!! Form::radio('status', '0') !!}　無効
    </div>
    -->
    
    
    <div class="form-group">
      {!! Form::submit('送信', ['class' => 'btn btn-primary form-control']) !!}
    </div>
  
  {!! Form::close() !!}
</div>
@endsection

resources/views/admin/column/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <h2>コラム追加</h2>
  
  {{-- エラーの表示を追加 --}}
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    
    
    
  {!! Form::open(array('files' => true)) !!}
  
    <div class="form-group">
      {!! Form::label('title', 'タイトル:') !!}
      {!! Form::text('title', $row->title, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
    @if ($row->image)
      <img src="/images/column/200-{{$row->image}}">
    @endif
      {!! Form::label('image', '画像:') !!}
      {!! Form::file('image', null) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('article', '本文:') !!}
      {!! Form::textarea('article', $row->article, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('width', '横幅:') !!}
      {!! Form::text('width', $row->width, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('height', '高さ:') !!}
      {!! Form::text('height', $row->height, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('contribute_date', '投稿日時:') !!}
      {!! Form::text('contribute_date', $row->contribute_date, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    
    <!--  
    <div class="form-group">
      {!! Form::label('ステータス', 'ステータス:') !!}
    
      {!! Form::radio('status', '1', true) !!}有効　
      {!! Form::radio('status', '0') !!}　無効
    </div>
    -->
    
    
    <div class="form-group">
      {!! Form::submit('送信', ['class' => 'btn btn-primary form-control']) !!}
    </div>
  
  {!! Form::close() !!}
</div>
@endsection

resources/views/admin/column/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    
    <h2>コラム一覧</h2>
    
    @if (Session::has('flash_message'))
      <div class="alert alert-success">{{ Session::get('flash_message') }}</div>
    @endif
    

    
    
    {!! $results->render() !!}
    　　　　<div class="pagination"><a href="{{ url('/admin/column/add') }}" class="btn btn-primary">コラムを追加する</a></div>
      
      <table  class="table">
		<tr>
			<td>ID</td>
        	<td>日付</td>
        	<td>タイトル</td>
           	<td>編集</td>
        	<td>削除</td>

        </tr>
    @foreach($results as $result)
        <tr>
        	<td>{{ $result->id }}</td>
        	<td>{{ $result->contribute_date }}</td>
        	<td>{{ $result->title }}</a></td>
        	<td><a href="{{ url('/admin/column/') }}/{{ $result->id }}/edit" class="btn btn-primary">編集</a></td>
        	<td><a href="{{ url('/admin/column/') }}/{{ $result->id }}/delete" class="btn btn-primary" data-toggle="confirmation" onclick="window.confirm('本当に削除しますか？')">削除</a></td>
        </tr>

    @endforeach
    </table>
    
</div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            	Welcome!! {{ Auth::guard('admin')->user()->name1 }} {{ Auth::guard('admin')->user()->name2 }} 
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            {{-- フラッシュメッセージの表示 --}}
            @if (Session::has('flash_message'))
              <div class="alert alert-success">{{ Session::get('flash_message') }}</div>
            @endif
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/admin/login') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}">

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-sign-in"></i>Login
                                </button>

                                <!-- <a class="btn btn-link" href="{{ url('/password/reset') }}">Forgot Your Password?</a> -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/add.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <h2>商品情報追加</h2>
  
  {{-- エラーの表示を追加 --}}
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    
    
    
  {!! Form::open(array('files' => true)) !!}
  
    <div class="form-group">
      {!! Form::label('maker', 'メーカー名:') !!}
      {!! Form::text('maker', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('productName', '製品名:') !!}
      {!! Form::text('productName', null, ['class' => 'form-control']) !!}
    </div>
    
   <div class="form-group">
      {!! Form::label('image', '外観画像:') !!}
      {!! Form::file('image', null) !!}
   </div>
   
   <div class="form-group">
      {!! Form::label('sellSituation', '発売状況:') !!}
      {!! Form::select('sellSituation', $arrParam['sellSituation'], null, ['class' => 'form-control']) !!}
   </div>
   
   <div class="form-group">
      {!! Form::label('price', '価格:') !!}
      {!! Form::text('price', null, ['class' => 'form-control']) !!}
   </div>
        
    <div class="form-group">
      {!! Form::label('feature', '製品の特長:') !!}
      {!! Form::textarea('feature', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('element', '想定要素:') !!}
      {!! Form::select('element', $arrParam['element'], null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('methodPrinting', '印刷方式:') !!}
      {!! Form::select('methodPrinting', $arrParam['methodPrinting'], null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('colorMaterial', '利用色材:') !!}
      {!! Form::select('colorMaterial', $arrParam['colorMaterial'], null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('methodTransport', '用紙搬送方式:') !!}
      {!! Form::select('methodTransport', $arrParam['methodTransport'], null, ['class' => 'form-control']) !!}
    </div>
   
   <div class="form-group">
      {!! Form::label('printSpeed', '印刷速度/搬送速度:') !!}
      {!! Form::text('printSpeed', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('resolution', '出力解像度:') !!}
      {!! Form::text('resolution', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('colors', '印刷色数:') !!}
      {!! Form::text('colors', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('media', '対応媒体種類:') !!}
      {!! Form::text('media', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('paperPressure', '対応用紙圧/用紙坪量/用紙斤量:') !!}
      {!! Form::text('paperPressure', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('paperSize', '対応用紙サイズ:') !!}
      {!! Form::text('paperSize', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('printSize', '印刷サイズ:') !!}
      {!! Form::text('printSize', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('outputNumber', '月間標準出力枚数:') !!}
      {!! Form::text('outputNumber', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('controller', 'コントローラ種類:') !!}
      {!! Form::text('controller', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('changeColor', '色数変更:') !!}
      {!! Form::text('changeColor', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('optionPaper', '給紙オプション:') !!}
      {!! Form::text('optionPaper', null, ['class' => 'form-control']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('optionProcessing', '加工オプション:') !!}
      {!! Form::text('optionProcessing', null, ['class' => 'form-control']) !!}
    </div>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <!--  
    <div class="form-group">
      {!! Form::label('Image1') !!}
      {!! Form::file('image1', null) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('Image2') !!}
      {!! Form::file('image2', null) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('Image3') !!}
      {!! Form::file('image3', null) !!}
    </div>
    
    -->
    
    <div class="form-group">
      {!! Form::submit('送信', ['class' => 'btn btn-primary form-control']) !!}
    </div>
  
  {!! Form::close() !!}
</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    
    <h2>商品情報一覧</h2>
    
    
    
    @if (Session::has('flash_message'))
      <div class="alert alert-success">{{ Session::get('flash_message') }}</div>
    @endif
    
    {{-- エラーの表示を追加 --}}
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    
    {!! Form::open(array('files' => true)) !!}
    <div class="panel panel-primary">
      <div class="panel-heading">検索する</div>
      <div class="panel-body">
        <div class="form-group email required user_basic_email">
          <label class="email required control-label" for="user_basic_email">
               　　　　　　　　
          </label>
          <input class="form-control" id="search" name="search" placeholder="メーカー、製品名から検索">
        </div>
      <input class="btn btn-default" name="commit" type="submit" value="検索">
      </div>
    </div>
    {!! Form::close() !!}
    
    {!! $results->render() !!}
    　　　　<div class="pagination"><a href="{{ url('/admin/product/add') }}" class="btn btn-primary">商品情報を追加する</a></div>
      
      <table  class="table">
		<tr>
			<td>画像</td>
        	<td>メーカー名</td>
        	<td>製品名</td>
           	<td>編集</td>
        	<td>削除</td>

        </tr>
    @foreach($results as $result)
        <tr>
            <td><img src="/images/product/200-{{ $result->image }}"></td>
        	<td>{{ $result->maker }}</td>
        	<td>{{ $result->productName }}</a></td>
        	
        	<!--<td>{!! link_to(action('AdminNewsController@edit', [$result->id]), '編集', ['class' => 'btn btn-primary']) !!}</td>-->
        	<td><a href="{{ url('/admin/product/') }}/{{ $result->id }}/edit" class="btn btn-primary">編集</a></td>
			<td><a href="{{ url('/admin/product/') }}/{{ $result->id }}/delete" class="btn btn-primary" data-toggle="confirmation" onclick="window.confirm('本当に削除しますか？')">削除</a></td>
        </tr>

    @endforeach
    </table>
    
</div>
@endsection

resources/views/admin/user/changePassword.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <h2>パスワード変更</h2>
  
  {{-- エラーの表示を追加 --}}
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    
    
    
  {!! Form::open() !!}
  
      
    <div class="form-group">
      {!! Form::label('password', '新しいパスワード:') !!}
      {!! Form::text('password', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::label('password_confirmation', '新しいパスワード(確認用):') !!}
      {!! Form::text('password_confirmation', null, ['class' => 'form-control ckeditor']) !!}
    </div>
    
    <div class="form-group">
      {!! Form::submit('変更', ['class' => 'btn btn-primary form-control']) !!}
    </div>
  
  {!! Form::close() !!}
</div>
@endsection

resources/views/keihi/detail.blade.php
<html>
<head>
    <title>詳細</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
</head>
<body>
<div class="ui main container">
    <div class="ui segment">
    <h1>詳細</h1>
    @if (isset($keihi->id))
    <table class="ui celled table">
        <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>価格</th>
            <th>URL</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{{ $keihi->id }}}</td>
                <td>{{{ $keihi->title }}}</td>
                <td>{{{ $keihi->price }}}</td>
                <td>{{{ $keihi->url }}}</td>
            </tr>
        </tbody>
    </table>
    <a class="ui primary button" href="{{ route('keihi.edit', ['id' => $keihi->id]) }}">編集</a>
    @endif
    <a class="ui button" href="/keihi">一覧へ戻る</a>
    </div>
</div>
</body>
</html>

resources/views/keihi/edit.blade.php
<html>
<head>
    <title>詳細</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
</head>
<body>
<div class="ui main container">
    <div class="ui segment">
    <h1>@if (isset($keihi->id))編集 @else 新規作成 @endif </h1>
    <form class="ui form" method="post" action="@if (isset($keihi->id)){{{ route('keihi.update', ['id' => $keihi->id]) }}} @else{{{ route('keihi.store') }}} @endif">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    @if (isset($keihi->id))<input name="_method" type="hidden" value="PUT"> @endif
    <table class="ui celled table">
        <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>価格</th>
            <th>URL</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{{ $keihi->id or '-'}}}</td>
                <td><input name="title" type="text" value="{{{ $keihi->title or ''}}}"></td>
                <td><input name="price" type="text" value="{{{ $keihi->price or ''}}}"></td>
                <td><input name="url" type="text" value="{{{ $keihi->url or ''}}}"></td>
            </tr>
        </tbody>
    </table>
    <input type="submit" class="ui primary button" value="@if (isset($keihi->id))更新 @else 作成 @endif">
    <a class="ui button" href="/keihi">キャンセル</a>
    </form>
    @if (isset($keihi->id))
    <form class="ui form" method="POST" action="{{{ route('keihi.destroy', ['id' => $keihi->id]) }}}">
     <input name="_method" type="hidden" value="DELETE">
     <input type="hidden" name="_token" value="{{ csrf_token() }}">
     <input type="submit" class="ui negative button" value="削除">
    </form>
    @endif
    </div>
</div>
</body>
</html>

resources/views/keihi/list.blade.php
<html>
<head>
    <title>一覧</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
</head>
<body>
<div class="ui main container">
    <div class="ui segment">
    <h1>一覧</h1>
    <a class="ui primary button" href="{{ route('keihi.create') }}">新規登録</a>
    <table class="ui celled table">
        <thead>
        <tr>
            <th>タイトル</th>
            <th>詳細</th>
        </tr>
        </thead>
        <tbody>
        @foreach($list as $keihi)
            <tr>
                <td>{{{ $keihi->title }}}</td>
                <td><a href="{{ route('keihi.show', ['id' => $keihi->id]) }}">詳細</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
</div>
</body>
</html>